<?php
/*
 * @ https://github.com/CMSNTSourceCode
 * @ Meo Mat Cang
 * @ PHP 7.4
 * @ Telegram : @Mo_Ho_Bo
 */
define("IN_SITE", true);
require_once __DIR__ . "/libs/db.php";
require_once __DIR__ . "/libs/lang.php";
require_once __DIR__ . "/config.php";
require_once __DIR__ . "/libs/helper.php";
$CMSNT = new DB();
$CMSNT->query(" ALTER TABLE `payment_momo` CHANGE `id` `id` INT(11) NOT NULL AUTO_INCREMENT ");
insert_options("check_time_cron_task", 0);
insert_options("thoi_gian_mua_cach_nhau", 3);
insert_options("max_register_ip", 5);
$CMSNT->query(" ALTER TABLE `suppliers` ADD `check_string_api` VARCHAR(55) NOT NULL DEFAULT 'ON' AFTER `update_gettime` ");
insert_options("time_cron_suppliers_api20", 0);
insert_options("status_menu_tools", 0);
insert_options("debug_auto_bank", 0);
$CMSNT->query(" ALTER TABLE `product_order` ADD `note` TEXT NULL DEFAULT NULL AFTER `api_transid` ");
insert_options("time_cron_suppliers_api9", 0);
insert_options("debug_api_suppliers", 1);
insert_options("order_by_product_home", 1);
insert_options("token_webhook_web2m", "");
insert_options("time_cron_suppliers_api21", 0);
$CMSNT->query(" ALTER TABLE `products` ADD `text_txt` TEXT NULL DEFAULT NULL AFTER `api_time_update` ");
$CMSNT->query(" ALTER TABLE product_die DROP INDEX uid ");
$CMSNT->query(" ALTER TABLE product_die ADD UNIQUE (uid) ");
insert_options("time_cron_suppliers_api17", 0);
$CMSNT->query(" ALTER TABLE `products` ADD `order_by` INT(11) NOT NULL DEFAULT '1' AFTER `text_txt` ");
insert_options("api_check_live_gmail", "");
insert_options("api_key_check_live_gmail", "");
insert_options("time_cron_checklive_gmail", 0);
insert_options("time_limit_check_live_gmail", 1800);
$CMSNT->query(" ALTER TABLE `product_sold` ADD `type` VARCHAR(55) NULL DEFAULT 'WEB' AFTER `time_check_live` ");
insert_options("widget_zalo1_status", 0);
insert_options("widget_zalo1_sdt", "");
insert_options("widget_phone1_status", 0);
insert_options("widget_phone1_sdt", "");
$CMSNT->query(" CREATE TABLE `payment_flutterwave` ( `id` INT NOT NULL AUTO_INCREMENT , `user_id` INT(11) NOT NULL DEFAULT '0' , `tx_ref` VARCHAR(55) NULL DEFAULT NULL , `amount` FLOAT NOT NULL DEFAULT '0' , `currency` TEXT NULL DEFAULT NULL , `create_gettime` DATETIME NOT NULL , `update_gettime` DATETIME NOT NULL , `status` VARCHAR(55) NOT NULL DEFAULT 'pending' , PRIMARY KEY (`id`)) ");
insert_options("flutterwave_status", 0);
insert_options("flutterwave_rate", 16);
insert_options("flutterwave_currency_code", "NGN");
insert_options("flutterwave_publicKey", "");
insert_options("flutterwave_secretKey", "");
insert_options("flutterwave_notice", "");
insert_options("limit_block_ip_login", 5);
insert_options("limit_block_client_login", 10);
$CMSNT->query(" CREATE TABLE `failed_attempts` ( `id` INT NOT NULL AUTO_INCREMENT , `ip_address` VARCHAR(45) NULL DEFAULT NULL , `attempts` INT(11) NOT NULL DEFAULT '0' , `create_gettime` DATETIME NOT NULL , `type` VARCHAR(55) NULL DEFAULT NULL , PRIMARY KEY (`id`)) ");
insert_options("limit_block_ip_api", 20);
insert_options("limit_block_ip_admin_access", 5);
insert_options("time_cron_suppliers_api22", 0);
insert_options("isPurchaseIpVerified", 0);
insert_options("isPurchaseDeviceVerified", 0);
$CMSNT->query(" CREATE TABLE `payment_manual` ( `id` INT NOT NULL AUTO_INCREMENT , `icon` TEXT NULL DEFAULT NULL , `title` TEXT NULL DEFAULT NULL , `description` TEXT NULL DEFAULT NULL , `content` LONGTEXT NULL DEFAULT NULL , `display` INT(11) NOT NULL DEFAULT '0' , `create_gettime` DATETIME NOT NULL , `update_gettime` DATETIME NOT NULL , PRIMARY KEY (`id`)) ");
$CMSNT->query(" ALTER TABLE `payment_manual` ADD `slug` TEXT NULL DEFAULT NULL AFTER `title` ");
$CMSNT->query(" ALTER TABLE `log_ref` CHANGE `id` `id` INT(11) NOT NULL AUTO_INCREMENT, add PRIMARY KEY (`id`) ");
insert_options("footer_card", "<a href=\"#\"><img src=\"/public/client/images/payment/jpg/01.jpg\" alt=\"payment\"></a>\n<a href=\"#\"><img src=\"/public/client/images/payment/jpg/02.jpg\" alt=\"payment\"></a>\n<a href=\"#\"><img src=\"/public/client/images/payment/jpg/03.jpg\" alt=\"payment\"></a>\n<a href=\"#\"><img src=\"/public/client/images/payment/jpg/04.jpg\" alt=\"payment\"></a>");
insert_options("notice_orders", "");
$CMSNT->query(" ALTER TABLE `menu` ADD `parent_id` INT(11) NOT NULL DEFAULT '0' AFTER `id` ");
insert_options("widget_fbzalo2_status", 0);
insert_options("widget_fbzalo2_zalo", "");
insert_options("widget_fbzalo2_fb", "");
$CMSNT->query(" ALTER TABLE `payment_flutterwave` ADD `price` FLOAT NOT NULL DEFAULT '0' AFTER `amount` ");
insert_options("time_cron_suppliers_api23", 0);
insert_options("show_btn_category_home", 0);
$CMSNT->query(" ALTER TABLE `suppliers` ADD `sync_category` VARCHAR(55) NOT NULL DEFAULT 'OFF' AFTER `update_name` ");
$CMSNT->query(" ALTER TABLE `categories` ADD `supplier_id` INT(11) NOT NULL DEFAULT '0' AFTER `id_api` ");
insert_options("time_cron_suppliers_api24", 0);
insert_options("status_only_ip_login_admin", 1);
insert_options("time_cron_checklive_instagram", 0);
insert_options("check_time_cron_thesieure", 0);
$CMSNT->query(" CREATE TABLE `payment_thesieure` ( `id` INT NOT NULL AUTO_INCREMENT , `method` VARCHAR(55) NULL DEFAULT NULL , `tid` VARCHAR(55) NOT NULL , `description` TEXT NULL DEFAULT NULL , `amount` INT(11) NOT NULL DEFAULT '0' , `received` INT(11) NOT NULL DEFAULT '0' , `create_gettime` DATETIME NOT NULL , `create_time` INT(11) NOT NULL DEFAULT '0' , `user_id` INT(11) NOT NULL DEFAULT '0' , `notication` INT(11) NOT NULL DEFAULT '0' , PRIMARY KEY (`id`), UNIQUE (`tid`)) ");
insert_options("thesieure_status", 0);
insert_options("thesieure_number", "");
insert_options("thesieure_email", "");
insert_options("thesieure_token", "");
insert_options("thesieure_notice", "");
insert_options("thesieure_name", "");
$CMSNT->query(" ALTER TABLE `products` ADD `allow_api` INT(11) NOT NULL DEFAULT '1' AFTER `order_by` ");
if($CMSNT->site("crypto_token") != "") {
    insert_options("crypto_type_api", "fpayment.co");
} else {
    insert_options("crypto_type_api", "fpayment.net");
}
insert_options("crypto_merchant_id", "");
insert_options("crypto_api_key", "");
insert_options("time_cron_suppliers_api25", 0);
insert_ip_block("27.75.226.17", "IP PHÁ HOẠI, KHÔNG ĐƯỢC XÓA");
insert_options("api_check_live_instagram", "");
insert_options("api_key_check_live_instagram", "");
insert_options("time_limit_check_live_instagram", 10);
$CMSNT->query(" ALTER TABLE `users` ADD `remember_token` VARCHAR(255) NULL DEFAULT NULL AFTER `token` ");
insert_options("isLoginRequiredToViewProduct", 0);
$CMSNT->query(" ALTER TABLE `product_sold` CHANGE `uid` `uid` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL ");
insert_options("telegram_assistant_status", 0);
insert_options("telegram_assistant_token", "");
insert_options("telegram_assistant_list_username", "");
insert_options("telegram_assistant_secret_token", generateUltraSecureToken(32));
insert_options("telegram_assistant_LicenseKey", "");
$CMSNT->query(" ALTER TABLE `users` ADD `reason_banned` TEXT NULL DEFAULT NULL AFTER `banned` ");
$CMSNT->query(" CREATE TABLE IF NOT EXISTS `telegram_logs` (\n    `id` INT AUTO_INCREMENT PRIMARY KEY,\n    `username` VARCHAR(255) DEFAULT NULL,\n    `command`  VARCHAR(100) DEFAULT NULL,\n    `params`   TEXT DEFAULT NULL,\n    `type`     VARCHAR(50) DEFAULT NULL,\n    `time`     DATETIME DEFAULT NULL\n) ");
$CMSNT->query(" ALTER TABLE `product_order` ADD `commission_fee` FLOAT NOT NULL DEFAULT '0' AFTER `cost` ");
$CMSNT->query(" ALTER TABLE `languages` ADD `code` VARCHAR(55) NULL DEFAULT NULL AFTER `lang` ");
insert_options("status_only_device_client", 1);
insert_options("status_only_device_admin", 1);
insert_options("is_uid_visible", 1);
insert_options("list_network_topup_card", "VIETTEL|Viettel\nVINAPHONE|Vinaphone\nMOBIFONE|Mobifone\nVNMOBI|Vietnamobile\nZING|Zing\nVCOIN|Vcoin\nGARENA|Garena (chỉ nhận thẻ trên 10k)\n");
$CMSNT->query(" CREATE TABLE `payment_xipay` (\n  `id` INT AUTO_INCREMENT PRIMARY KEY,\n  `out_trade_no` VARCHAR(64) NOT NULL,\n  `transaction_id` VARCHAR(64) DEFAULT NULL COMMENT 'Mã giao dịch do Xipay trả về',\n  `type` VARCHAR(20) DEFAULT NULL COMMENT 'Phương thức thanh toán (alipay, wxpay...)',\n  `price` DECIMAL(10,2) NOT NULL DEFAULT '0.00' COMMENT 'Số tiền thực nhận',\n  `amount` DECIMAL(10,2) NOT NULL DEFAULT '0.00' COMMENT 'Số tiền thanh toán',\n  `param` VARCHAR(255) DEFAULT NULL COMMENT 'Tham số mở rộng',\n  `product_name` VARCHAR(255) DEFAULT NULL COMMENT 'Tên sản phẩm/dịch vụ',\n  `status` TINYINT DEFAULT 0 COMMENT 'Trạng thái giao dịch: 0=pending,1=success,2=fail...',\n  `notify_data` TEXT DEFAULT NULL COMMENT 'Lưu dữ liệu notify (nếu cần)',\n  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  `user_id` INT DEFAULT NULL COMMENT 'ID user trong hệ thống (nếu có)'\n) ");
insert_options("gateway_xipay_status", 0);
insert_options("xipay_notice", "");
insert_options("xipay_min", 1);
insert_options("xipay_max", 1000000);
insert_options("gateway_xipay_md5key", "");
insert_options("gateway_xipay_pid", "");
insert_options("gateway_xipay_rate", 3508);
insert_options("gateway_xipay_license", "");
$CMSNT->query(" ALTER TABLE `payment_xipay` ADD `notication` INT(11) NOT NULL DEFAULT '0' AFTER `user_id` ");
$CMSNT->query(" CREATE TABLE admin_request_logs (\n    id INT AUTO_INCREMENT PRIMARY KEY,\n    user_id INT,\n    request_url TEXT NOT NULL,\n    request_method VARCHAR(10) NOT NULL,\n    request_params TEXT,\n    ip VARCHAR(45) NOT NULL,\n    user_agent TEXT NOT NULL,\n    timestamp DATETIME NOT NULL\n) ");
insert_options("korapay_status", 0);
insert_options("korapay_secretKey", "");
insert_options("korapay_min", 1);
insert_options("korapay_max", 1000000);
insert_options("korapay_notice", "");
insert_options("korapay_currency_code", "NGN");
insert_options("korapay_rate", 17);
insert_options("korapay_proxy", "");
insert_options("korapay_license", "");
$CMSNT->query(" CREATE TABLE `payment_korapay` (\n    `id` INT AUTO_INCREMENT PRIMARY KEY,\n    `trans_id` VARCHAR(64) NOT NULL,\n    `price` DECIMAL(10,2) NOT NULL DEFAULT '0.00' COMMENT 'Số tiền thực nhận',\n    `amount` DECIMAL(10,2) NOT NULL DEFAULT '0.00' COMMENT 'Số tiền thanh toán',\n    `status` TINYINT DEFAULT 0 COMMENT 'Trạng thái giao dịch: 0=pending,1=success,2=fail...',\n    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,\n    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n    `user_id` INT DEFAULT NULL,\n    `checkout_url` VARCHAR(255) NOT NULL,\n    `notication` INT(11) NOT NULL DEFAULT 0\n  ) ");
insert_options("tmweasyapi_status", 0);
insert_options("tmweasyapi_username", "");
insert_options("tmweasyapi_password", "");
insert_options("tmweasyapi_con_id", "");
insert_options("tmweasyapi_license", "");
insert_options("tmweasyapi_rate", 756);
insert_options("tmweasyapi_notice", "");
insert_options("tmweasyapi_min", 1);
insert_options("tmweasyapi_max", 1000000);
$CMSNT->query(" CREATE TABLE `payment_tmweasyapi` (\n`id` INT AUTO_INCREMENT PRIMARY KEY,\n`trans_id` VARCHAR(64) NOT NULL,\n`price` INT(11) NOT NULL DEFAULT 0 COMMENT 'Số tiền thực nhận',\n`amount` INT(11) NOT NULL DEFAULT 0 COMMENT 'Số tiền thanh toán',\n`status` TINYINT DEFAULT 0 COMMENT 'Trạng thái giao dịch: 0=pending,1=success,2=fail...',\n`created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,\n`updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n`user_id` INT DEFAULT NULL,\n`checkout_url` VARCHAR(255) NOT NULL,\n`notication` INT(11) NOT NULL DEFAULT 0\n) ");
$CMSNT->query(" ALTER TABLE `payment_tmweasyapi` ADD `id_pay` VARCHAR(55) NULL DEFAULT NULL AFTER `notication` ");
insert_options("chatgpt_api_key", "");
insert_options("chatgpt_model", "gpt-3.5-turbo");
$CMSNT->query(" CREATE TABLE `payment_openpix` (\n    `id` INT AUTO_INCREMENT PRIMARY KEY,\n    `trans_id` VARCHAR(64) NOT NULL,\n    `price` INT(11) NOT NULL DEFAULT 0 COMMENT 'Số tiền thực nhận',\n    `amount` DECIMAL(10,2) NOT NULL DEFAULT '0.00' COMMENT 'Số tiền thanh toán',\n    `status` TINYINT DEFAULT 0 COMMENT 'Trạng thái giao dịch: 0=pending,1=success,2=fail...',\n    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,\n    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n    `user_id` INT DEFAULT NULL,\n    `checkout_url` VARCHAR(255) NOT NULL,\n    `notication` INT(11) NOT NULL DEFAULT 0\n    ) ");
insert_options("openpix_status", 0);
insert_options("openpix_api_key", "");
insert_options("openpix_HMAC_key", "");
insert_options("openpix_HMAC_key_completed", "");
insert_options("openpix_license", "");
insert_options("openpix_rate", 4357);
insert_options("openpix_notice", "");
insert_options("openpix_min", 1);
insert_options("openpix_max", 1000000);
$CMSNT->query(" ALTER TABLE `suppliers` ADD `proxy` TEXT NULL DEFAULT NULL AFTER `update_name` ");
insert_options("limit_block_ip_reset_password", 10);
insert_options("limit_block_ip_otp", 10);
insert_options("limit_block_ip_2fa", 10);
insert_options("task_24h", 0);
insert_options("limit_block_ip_spam", 10);
insert_options("limit_block_ip_payment", 10);
$CMSNT->query(" CREATE TABLE `payment_bakong` (\n    `id` INT AUTO_INCREMENT PRIMARY KEY,\n    `trans_id` VARCHAR(64) NOT NULL,\n    `price` INT(11) NOT NULL DEFAULT 0 COMMENT 'Số tiền thực nhận',\n    `amount` DECIMAL(10,2) NOT NULL DEFAULT '0.00' COMMENT 'Số tiền thanh toán',\n    `status` TINYINT DEFAULT 0 COMMENT 'Trạng thái giao dịch: 0=pending,1=success,2=fail...',\n    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,\n    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n    `user_id` INT DEFAULT NULL,\n    `checkout_url` VARCHAR(255) NOT NULL,\n    `notication` INT(11) NOT NULL DEFAULT 0\n    ) ");
insert_options("bakong_status", 0);
insert_options("bakong_profile_id", "");
insert_options("bakong_profile_key", "");
insert_options("bakong_license", "");
insert_options("bakong_rate", 25000);
insert_options("bakong_notice", "");
insert_options("bakong_min", 1);
insert_options("bakong_max", 1000000);
insert_options("icon_hotline", "<i class=\"fa-solid fa-phone\"></i>");
insert_options("icon_address", "<i class=\"fa-solid fa-location-dot\"></i>");
insert_options("icon_email", "<i class=\"fa-solid fa-envelope\"></i>");
insert_options("time_cron_suppliers_api26", 0);

?>